### ISSUE TITLE
As a user, I want the answers to be ranked so that the highest ranked answer is displayed first.

### ISSUE THREAD

**Issue by Josephj9720** [kaosalrim/SOEN341_Team_Project#11]
#8 Epic: Upvote/Downvote the answers.

Priority: Low
Story points: 5
Low risk: most of the design is done through #5. Functionality update required

Tasks:

- [ ] #60

**Comment by ayeshahrh** [comment]
### "As a user, I want the answers to be ranked so that the highest ranked answer is displayed first."
Acceptance Test:

- Go to Q&A website 
- Log into your account 
- Questions asked by all users of the website will be displayed on the front page 
- Click on any particular question to see all the answers
- Click on the upvote or downvote icons beside the answers box according to how useful you found the answers to be 
- The highest ranked answer will be the one with the most accumulated upvotes and will be displayed as the first answer for quicker access
