### ISSUE TITLE
Acceptance test for #11 and #64

### ISSUE THREAD

**Issue by kaosalrim** [kaosalrim/SOEN341_Team_Project#115]
Acceptance test for # 11 and #64

**Comment by ayeshahrh** [comment]
### "As a user I want to see the best answer to the question first in order to avoid scrolling"
Acceptance Test:

- Go to Q&A website 
- Log into your account
- Go to the section where all the questions you have asked are stored
- Click on any question to see all displayed answers from other users
- Pick which answer is the best answer by clicking the icon 
- Once the icon is clicked, the **best answer** will be automatically be displayed as the first answer when opening the question
